ECHO OFF
CLS
ECHO:
ECHO                C A T H A I R    B O O K S   S H A R E W A R E
ECHO:
ECHO:
ECHO:
ECHO:
ECHO          ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
ECHO          ³  This disc forms part of the Cathair Books Library of       ³
ECHO          ³      Selected Public Domain and Shareware programs.         ³
ECHO          ³                                                             ³
ECHO          ³  If you did not receive it directly from Cathair Books,     ³
ECHO          ³  please contact us - you may be missing out on the latest   ³
ECHO          ³  version and many other programs - new ones are added daily.³
ECHO          ³                                                             ³
ECHO          ³  CATHAIR BOOKS, 1 Essex Gate, Dublin 8. Tel 6792406         ³
ECHO          ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
ECHO:
ECHO:
ECHO:
ECHO           İİİİİİİ  BEFORE USING THIS DISC - MAKE A WORKING COPY  İİİİİİİ
ECHO:
PAUSE
CLS
ECHO ÛßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßÛ
ECHO Û To the best of our knowledge, programs and documentation on this disc have  Û
ECHO Û been released into the Public Domain or issued as Shareware.  The Cathair   Û
ECHO Û Books price covers promotional and distribution costs.  There is no charge  Û
ECHO Û for Public Domain software.  Shareware is supplied for you to evaluate and, Û
ECHO Û if you continue to use it, you should buy the registered version. In return Û
ECHO Û you can expect printed documentation, technical support and updates.        Û
ECHO Û                                                                             Û
ECHO Û Most programs were developed for use on an IBM PC XT running MSDOS v2.0 up. Û
ECHO Û They will run on all true compatibles.  Some require dual floppy or hard    Û
ECHO Û disc drives. Some require a Colour Graphics Adaptor, a Hercules Graphics    Û
ECHO Û Adaptor or an Extended Graphics Adaptor. If a program does not run, please  Û
ECHO Û check that your PC is compatible with requirements in the documentation.    Û
ECHO Û Most programs expect you to use an Epson or IBM-compatible printer.         Û
ECHO ÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛ
ECHO:
PAUSE
CLS
ECHO ÛßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßÛ
ECHO Û Please read the documentation on this disc.  It is usually in the form of a Û
ECHO Û file called README or ending in .TXT or .DOC. To view a file, use the LIST  Û
ECHO Û program, for example to view the file READ.ME, type LIST READ.ME [RETURN]   Û
ECHO Û To obtain printed copy press P.  Press ? for help with the LIST program.    Û
ECHO Û                                                                             Û
ECHO Û Program names end with a .BAT or .EXE or .COM extension.  They can be run   Û
ECHO Û by typing in just the program NAME (not the extension). Some discs contain  Û
ECHO Û a start up program called RUN.BAT.  If so, just type  RUN [RETURN]          Û
ECHO Û                                                                             Û
ECHO Û To run a CGA program on an EGA PC it may be necessary to set up CGA mode    Û
ECHO Û first.  Using your MSDOS System disc, type  DISPLAY CGA [RETURN]            Û
ECHO Û                                                                             Û
ECHO Û Some games offer a JOYSTICK/KEYBOARD option.  The joystick required is the  Û
ECHO Û IBM analogue variety which requires a special adaptor card.  In some cases, Û
ECHO Û on the Amstrad range, a standard switching joystick may be used but the     Û
ECHO Û KEYBOARD option must still be selected.                                     Û
ECHO Û                                                                             Û
ECHO Û Most programs offer proper MENU-based quit options; if not, try:-           Û
ECHO Û    Q   X   Esc   Ctrl C   Ctrl Break   Ctrl End   F10   F9   Ctrl Alt Del   Û
ECHO Û    To quit from BASIC press Ctrl Break and type SYSTEM [RETURN]             Û
ECHO ÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛ
ECHO:
PAUSE
CLS
ECHO ÛßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßÛ
ECHO Û If you are unsure how to use your PC to run these programs or do not        Û
ECHO Û understand how to use DOS we recommend you try our PC TUTOR disc.           Û
ECHO Û                                                                             Û
ECHO Û Please note that the programs on this disc are supplied as-is.  Whilst      Û
ECHO Û Cathair Books try to provide help where we can, we do not guarantee to      Û
ECHO Û offer technical support nor are we in a position to fix program errors.     Û
ECHO Û                                                                             Û
ECHO Û Cathair Books will not accept any liability whatever for damages or losses  Û
ECHO Û incurred as a result of using these programs. Our liability is limited to   Û
ECHO Û the provision of an error free copy of the master disc.                     Û
ECHO Û                                                                             Û
ECHO Û CATHAIR BOOKS, 1 Essex Gate, Dublin 8                                       Û
ECHO Û             Tel (01) 6792406                                                Û
ECHO Û                                                                             Û
ECHO ÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛ
ECHO:
PAUSE
CLS
ECHO:                   ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO:                   º    SPECTRUM EMULATOR     º
ECHO:                   º            by            º
ECHO:                   º      Kevin J. Phair      º
ECHO:                   º     28 Bancroft Road,    º
ECHO:                   º        Dublin 24.        º
ECHO:                   ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
          PAUSE
CLS
LIST SPECEM.DOC
ECHO  Here is a directory of this disc:-
ECHO:
DIR/P
